tarantool/expirationd

README.md, expirationd.lua, test.lua
* Added the ability to set iteration and full scan delays for a task.
* Added callbacks for a task at various stages of the full scan iteration.
@ChangeLog:
* Added the ability to set iteration and full scan delays for a task.
* Added callbacks for a task at various stages of the full scan iteration.
=> Implementation of call functions on iteration state

.travis.yml
Ubuntu Eoan is EOL and fails in CI on apt repositories updating with 'does not have a Release file' errors.
=> Remove Ubuntu Eoan from CI

expirationd.lua
Thread1:
```
s = box.schema.create_space('c', {
>         if_not_exists = true,
>     })
s:create_index('idx', {
>         type = 'tree',
>         unique = true,
>         parts = {
>             1, 'unsigned',
>         },
>         if_not_exists = true,
>     })
box.space.c:insert({1, 2})
d = box.space.c:select()
```
Thread2:
```
box.space.c:update(1, {
{'=', 1, 3},
})
```
Thread1:
```
> d
---
- - [1, 2]
```
=> Use actual data for expirations

.github/workflows/fast_testing.yaml, Makefile, README.md, expirationd.lua, test/helper.lua, test/unit/atomic_iteration_test.lua, test/unit/custom_index_test.lua, test/unit/iterate_with_test.lua, test/unit/iterator_type_test.lua, test/unit/process_while_test.lua, test/unit/start_key_test.lua
* Iterations over Secondary Indexes - name of the index to iterate on
* Transaction support - ability to process tuples from each batch in a single transaction
* Start key - start iterating from the tuple with this index value
* Iterator type - type of the iterator to use, as string or box.index constant
* Process while function - function to call before checking each tuple, if it returns false, the task will stop until next full scan
* And the ability to write custom iterator behavior for the user - `iterate_with` function which returns an iterator object which provides tuples to check
Additional changes:
Rewritten space iteration for tree index from select to pairs since the iterator is now stable
Added some comments and removed duplicate code(expirationd_kill_task)
Described new …
=> Features for more customized behavior

.github/workflows/fast_testing.yaml, .luacheckrc, Makefile, expirationd.lua, test/unit/atomic_iteration_test.lua
Added luacheck config and fixed a number of luacheck warnings.
Tarantool's Lua style guide allows to ignore some luacheck warnings [1].
File with TAP tests added to ignore list because we plan to rewrite
these tests to luatest style, see [2].
1. https://www.tarantool.io/en/doc/latest/dev_guide/lua_style_guide/#luacheck
2. https://github.com/tarantool/expirationd/issues/61
Closes #57
=> Enable Lua source code analysis with luacheck

expirationd.lua, test/unit/task_stop_test.lua
The problem is that the call to task:stop hangs, because task:stop
sends cancel to the active fibers and waits for these fibers to become
"dead". But there may be some code that can get cancelation using pcall
and skip it, so we have to check the fiber for cancellation.
We do this by checking a flag `worker_canceled` that was previously
only used for atomic iterations. We also fixed the places where this
flag is checked and added comments why in this or that place we
check the cancellation of the worker.
Closes #69
=> Fix freezes when stopping a task

Makefile, README.md, doc/ldoc/assets/ldoc.css, doc/ldoc/assets/ldoc.ltp, doc/ldoc/config.ld, expirationd.lua
Online: https://tarantool.github.io/expirationd/
Ticket: #79
=> Support LDoc

.github/workflows/fast_testing.yaml, .github/workflows/publish.yml, .gitignore, Makefile
Follows up #79 
I check publishing in a separate branch [gh-79-publish-ldoc-test](https://github.com/tarantool/expirationd/commits/ligurio/gh-79-publish-ldoc-test) that contains a visible change in documentation ("Hello, dude!"):
```
--- a/expirationd.lua
+++ b/expirationd.lua
@@ -1,4 +1,4 @@
---- expirationd - data expiration with custom quirks.
+--- expirationd - data expiration with custom quirks (Hello, dude!).
--
-- @module expirationd
```
And also [removes things that blocks workflow run and uploading rock to the server](https://github.com/tarantool/expirationd/commit/8d7baec73bc4cfdae8d102670dbaf75ade680226).
https://tarantool.github.io/expirationd/
=> Publish API documentation in Github Actions

expirationd-scm-1.rockspec
GitHub is going to disable unencrypted Git protocol, so `git://` URLs
will stop working soon (see [1]).
[1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Part of https://github.com/tarantool/tarantool/issues/6587
=> rockspec: use git+https:// for git repository URL

.github/workflows/reusable_testing.yml
The idea of this workflow is to be a part of the 'integration.yml'
workflow from the tarantool repo to verify the integration of the
expirationd module with an arbitrary tarantool version.
This workflow is not triggered on a push to the repo and cannot be run
manually since it has only the 'workflow_call' trigger. This workflow
will be included in the tarantool development cycle and called by the
'integration.yml' workflow from the tarantool project on a push to the
master and release branches for verifying integration of tarantool with
expirationd.
Part of tarantool/tarantool#6528
Part of tarantool/tarantool#5265
Part of tarantool/tarantool#6056
Workflow on Tarantool side: https://github.com/tarantool/tarantool/pull/6529
=> ci: add reusable testing workflow

test/helper.lua, test/unit/atomic_iteration_test.lua
Let's disable the 'test_mvcc_vinyl_tx_conflict' test due to #105.
The test is unstable and should be reworked.
=> test: disable test_mvcc_vinyl_tx_conflict

expirationd.lua, test/helper.lua, test/unit/custom_index_test.lua
expirationd.start fails with an error for a functional index if
a Tarantool instance version is less than 2.8.4. It can be disabled
using options.force_allow_functional_index.
Closes #101
An user can use options.force_broken + options.iterate_with to avoid the crash, see:
https://github.com/tarantool/expirationd/blob/a2bc3d39ea20197818170da1886adfdd3de4cfac/test/unit/custom_index_test.lua#L239-L245
=> Prevent iteration through a functional index for Tarantool < 2.8.4

expirationd.lua
The pull request fixes the description and behavior of `force` option for `expirationd.start`. It just closes actual problems, synchronizes the description and current logic. It does not change an old behavior.
It was a fix for #95, but the small piece code is connected with an other unresolved issue. It closes #92, #95, #96. The changes is very simple, but I can split the pull request if necessary.
=> Fix a description and behavior of the force option for expirationd.start

.github/workflows/fast_testing.yaml, Makefile, README.md, expirationd.lua, test/entrypoint/srv_reload.lua, test/helper.lua, test/integration/reload_test.lua, test/unit/cfg_test.lua, test/unit/metrics_test.lua
The patch adds the ability to export statistics to metrics >= 0.11.0. expirationd does not require the metrics package itself and tries to use an installed one.
It also adds a new API method expirationd.cfg({options}).
Closes #100
=> Add metrics for expirationd stats

.github/workflows/fast_testing.yaml
Now the workaround for https://github.com/tarantool/setup-tarantool/issues/19 is not needed, because tarantool-2.10+ releases are supported since setup-tarantool v1.3.0.
The action uses the GitHub's caching infrastructure to speed up tarantool installation.
=> ci: use setup-tarantool for 2.10

.github/workflows/fast_testing.yaml, .github/workflows/publish.yml, .github/workflows/reusable_testing.yml
The patch adds a Tarantool debug build from the last commit of the master branch to GitHub Actions workflow. It uses an official build instruction for Tarantool [1] and the cache action [2] to cache build outputs.
1. https://www.tarantool.io/ru/doc/latest/dev_guide/building_from_source/
2. https://github.com/actions/cache
Closes #102
=> ci: add a debug Tarantool build

Makefile, README.md, test/unit/cfg_test.lua, test/unit/metrics_test.lua, test/unit/task_stop_test.lua
PR introduces two changes:
1. shuffling tests in luatest
luatest has an option --shuffle that allows to randomise the order of
tests. This can be useful to detect a test that passes just because it
happens to run after an unrelated test that leaves the system in a
favourable state. Patch enable tests shuffling with predefined random
seed specified by $RANDOM. Seed is useful for reproducing problems
related to the specific test order.
2. bump luatest version
=> Shuffle tests

debian/control, expirationd-scm-1.rockspec
The patch updates the maintainer's name and email address for a rockspec and a debian package.
A previous one: https://github.com/tarantool/expirationd/commit/135f033bd09bafc7a9621a26e301b67ea9820cd6
=> repo: take maintairnership

expirationd.lua, test/integration/reload_test.lua, test/unit/continue_test.lua
After the patch a task continues processing from a last tuple at startup unless it was killed using `task:kill()` or `expirationd.kill()`. We cannot provide a safe behavior for all user cases, so it works only with default `start_key` and `iterate_with` callbacks.
The behavior supports a cartridge hot-reload.
Closes #54
A cartridge role is out of scope here and will be done for #107 . In the pull request just continue tasks + cartridge hot-reload tests for it.
=> api: continue a task from a last tuple

.github/workflows/packaging.yml, debian/control, debian/prebuild.sh, debian/rules, expirationd-scm-1.rockspec, rpm/prebuild.sh, rpm/tarantool-expirationd.spec
This workflow is intended to run on a tag push for creating and deploying module packages to S3 based repositories.
We don't have the tarantool-luatest package in any public repository for all supported distros. We have to skip the test step until the tarantool-luatest is built at least for S3 repository.
It also fixed tarantool-checks dependency for deb/rpm packages, decreases required tarantool-checks from 3.1 to 2.1.
See other similar pull requests:
https://github.com/tarantool/queue/pull/157 , https://github.com/tarantool/http/pull/164
Closes #43 
Closes #124
=> cd: add package deploy workflow

expirationd.lua, test/unit/custom_index_test.lua, test/unit/space_index_test.lua
After the patch an user can to start expirationd task disregarding whether a space (and a primary/requested index) is exists or not. expirationd does not start a worker fiber until the space or index appears.
Also, after the patch expirationd stops all task fibers if a space or an index configuration error happens:
* the space or the index disappears (drop/rename);
* an unsupported type of the index;
* an invalid iterator or a start key for the index;
Closes #64
Closes #68
Closes #116
=> api: wait until a space or an index is created

README.md, cartridge/roles/expirationd.lua, debian/tarantool-expirationd.install, expirationd-scm-1.rockspec, rpm/tarantool-expirationd.spec, test/entrypoint/srv_role.lua, test/integration/role_test.lua, test/unit/role_test.lua
`cartridge.roles.expirationd` is a Tarantool Cartridge role for the expirationd
package with the features:
* It registers expirationd as a Tarantool Cartridge service for easy access to
all [API calls](https://tarantool.github.io/expirationd/#Module_functions):
```Lua
local task = cartridge.service_get('expirationd').start("task_name", id, is_expired)
task:kill()
```
* The role stops all expirationd tasks on an instance on the role termination.
* The role can automatically start or kill old tasks from the role
configuration:
```yaml
expirationd:
task_name1:
space_id: 579
is_expired: is_expired_func_name_in__G
is_master_only: true
options:
args:
- any
atomic_iteration: false
force: false
force_allow_functional_index: true
full_scan_delay: 1
full_scan_time: 1
index: 0
iterate_with: …
```
=> cartridge: add a role

README.md, cartridge/roles/expirationd.lua, expirationd.lua, test/integration/role_test.lua, test/unit/role_test.lua, test/unit/space_index_test.lua
expirationd.start() has the parameter space_id. The parameter name is
confusing because the value can be a name of a space, not just id.
This change does not affect an old code:
* It changes the name of the parameter, not the key in the options
table. It doesn't break the current code.
* An user should not use a task.space_id field directly [1]. We are
free to rename it.
1. https://github.com/tarantool/expirationd/blob/b9bcbe0a1782ffc1225c33d1eab78ef4e60162f8/expirationd.lua#L420-L423
Closes #112
It is the time to make this correction (if we really want it) so that the name doesn't get into the Tarantool Cartridge role parameter:
https://github.com/tarantool/expirationd/blob/b9bcbe0a1782ffc1225c33d1eab78ef4e60162f8/README.md?plain=1#L167
After the 1.3.0 release, it will be more difficult …
=> api: rename space_id parameter to space

CHANGELOG.md, debian/changelog, rpm/tarantool-expirationd.spec
This release adds a Tarantool Cartridge role for expirationd package and improves the default behavior.
None.
* Obsolete functions: task_stats, kill_task, get_task, get_tasks, run_task, show_task_list.
* Continue a task from a last tuple (#54).
* Decrease tarantool-checks dependency from 3.1 to 2.1 (#124).
* Process a task on a writable space by default (#42).
* Wait until a space or an index is created (#68, #116).
* Tarantool Cartridge role (#107).
* Fix build and installation of rpm/deb packages (#124).
* Do not restart a work fiber if an index does not exist (#64). 
* Update changelogs.
* Shuffle tests (#118).
* Fix test_mvcc_vinyl_tx_conflict (#104, #105).
* Fix flaky 'simple expires test' (#90).
* expirationd.start() parameter `space_id` has been renamed to `space` (#112).
* Add …
=> Release 1.3.0

CHANGELOG.md, expirationd.lua, test/helper.lua, test/unit/custom_index_test.lua, test/unit/expirationd_stats_test.lua, test/unit/iterator_type_test.lua, test/unit/start_key_test.lua
The function may return true for Tarantool 2.11. It is incorrect
because the bug was fixed in 2.10:
...
1.10   1.10.11-5-g40d8f4df1
...
2.8    2.8.2-12-g2663a9c6c
2.10   2.10.0-beta1-51-g0428bbcef
master 2.10.0-beta1-51-g0428bbcef
The patch fixes the problem and unifies a code that checks a support
of features.
Closes #103
=> test: fix vinyl_is_broken() check

CHANGELOG.md, README.md, cartridge/roles/expirationd.lua, test/unit/role_test.lua
A user can configure the role using the `cfg` entry. The configuration options are the same as for expirationd.cfg().
The `cfg` entry may be a task for backward compatibility.
Closes #131
=> cartridge: ability to configure the role

test.lua, test/helper.lua, test/unit/expiration_process_test.lua
Check if we can use specific is_tuple_expired, process_expired_tuple, these basic functions are included in expiration_process. Function is_tuple_expired checks the timestamp in the time field of tuple, and if current time is greater then time field then true. Function process_expired_tuple instead of simple deletion, does the archiving by deleting the tuple from the expirated space and insert into a new space that we create in before_each.
- simple expires test -> test_archive_by_timestamp
Part of #61
=> test: archive_by_timestamp

CHANGELOG.md, debian/changelog, expirationd/version.lua, rpm/tarantool-expirationd.spec
The release adds `_VERSION` constant for the module.
None.
* Add versioning support (https://github.com/tarantool/expirationd/pull/136).
=> Release 1.4.0

test/integration/reload_test.lua
A last Tarantool version include metrics itself. The behavior is different and the metrics contains information about Tarantool. We need to take this into account to fix the test.
Closes #142
=> test: fix test_cfg_metrics_clean_after_reload

test.lua, test/helper.lua, test/unit/expiration_process_test.lua
- execution error test -> test_broken_is_tuple_expired -> test_broken_process_expired_tuple
Part of #61
=> test: pass broken function in parameters

test.lua, test/unit/expiration_process_test.lua
Transferring the taptest to the luatest testing system with renaming the
tests and using the existing spaces in helpers.
Check that the task will expirate as many tuples in one batch as we
specify in tuples_per_iteration and sleep between iterations.
- multiple expires test -> test_tuples_per_iteration
Part of https://github.com/tarantool/expirationd/issues/61
=> test: tuples_per_iteration

test.lua, test/unit/callbacks_and_delays_test.lua
Check that there is suspend between batches/iterations and between fullcans. We will also calculate whether success callbacks are called correctly.
- delays and scan callbacks test -> test_delays_and_scan_callbacks
Part of #61
=> test: delays_and_scan_callbacks

test.lua, test/helper.lua, test/unit/callbacks_and_delays_test.lua, test/unit/expiration_process_test.lua
Let's calculate whether callbacks are called correctly in case of an error.
- error callback test -> test_error_callback
Part of #61
=> test: error_callback

.gitignore, test.lua
This test checks the expiration of the space by multipart index.
A test with the same functionality exists in [1].
1. Iterate over any index https://github.com/tarantool/expirationd/commit/4f44e1b88e12a2a0346684cbda226e365da6167b
Part of https://github.com/tarantool/expirationd/issues/61
=> test: delete complex key test

test.lua, test/unit/update_and_kill_test.lua
Check if the expirationd module will work correctly on time and after expirationd.update.
Also fixed error in task_stop_test, a bug that affected the update test.
Updated test's names:
- restart test -> test_expirationd_update
Part of #61
=> test: expirationd_update

CHANGELOG.md, README.md, cartridge/roles/expirationd.lua, test/helper.lua, test/integration/role_test.lua, test/unit/role_test.lua
A user can configure the role with persistent functions as callback for task.
Closes #153
=> cartridge: ability to use persistent functions

CHANGELOG.md, debian/changelog, expirationd/version.lua, rpm/tarantool-expirationd.spec
The release adds an ability to use functions from `box.func` with the Tarantool Cartridge role.
None.
* An ability to use persistent functions in `box.func` with cartridge. A user can configure the role with persistent functions as callback for a task (#153).
=> Release 1.5.0

CHANGELOG.md, test/helper.lua, test/unit/space_index_test.lua
If the tarantool/tarantool#8751 is merged, the space drop is transactional, so it only yields once on the space drop operation finish. This causes the test fail [1] because of unexpected state in the expirationd task.
This patch fixes the problem by wrapping space drop and recreation into a transaction.
More informative description of what the issue is:
Consider the following facts:
1. If the PR mentioned above is merged, the space drop yields on the full DDL operation end. After that point, the space is dropped entirely (no indexes or entries in the `_space` space exist).
2. If the expirationd task's `atomic_iteration` option is set to false (which is the default used in the test), each tuple drop causes the expirationd task fiber yield.
So here's what happens if the fact 1 is false (the …
=> test: align space_index_test with the transactional DDL

CHANGELOG.md, expirationd/version.lua
The release introduces a role for Tarantool 3.0.
None.
* Tarantool 3.0 role (#160).
* Updated the 'space_index_test.lua' to drop and recreate the test space atomically. This prevents the space access failure in the expirationd task fiber if the `space:drop` function is transactional (#157).
* Updated version of `luatest` in `make deps` to 1.0.1 to support Tarantool 3.0 role tests (#160).
=> Release 1.6.0

README.md
`roles_cfg` should be on the same level as `roles`. Now README provides invalid yaml (`roles` key has values of two types simultaneously).
Follows #160
=> readme: fix Tarantool 3 config example

CHANGELOG.md, expirationd/version.lua
- Added the ability to run without a user Lua-code.
- Fix `is_master_only` option. Now it runs on master correctly. 
- Fixed restrictions on the order of role enable.
=> release 1.7.0
